const PLAN_CODES = {
  FREE: 'free',
  PREMIUM: 'premium',
};

const SUBSCRIPTION_STATES = {
  FREE: 'free',
  PREMIUM_ACTIVE: 'premium_active',
  PREMIUM_CANCEL_SCHEDULED: 'premium_cancel_scheduled',
  CLEANUP_REQUIRED: 'cleanup_required',
};

const RENEWAL_MODES = {
  MANUAL: 'manual',
  AUTOMATIC: 'automatic',
};

const RENEWAL_STATUSES = {
  DISABLED: 'disabled',
  PENDING_SETUP: 'pending_setup',
  ACTIVE: 'active',
  PAUSED: 'paused',
};

const RENEWAL_PROVIDERS = {
  ETHEREUM_WALLET: 'ethereum_wallet',
};

const BILLING_PERIOD_DAYS = 30;
const PREMIUM_DURATION_MONTHS = Number(process.env.PREMIUM_DURATION_MONTHS || 1);
const ETH_CHAIN_ID = 31337;
const ETH_NETWORK_NAME = 'Anvil Mainnet Fork';
const USDC_TOKEN_ADDRESS = process.env.USDC_MAINNET_ADDRESS || null;
const SUBSCRIPTION_CORE_ADDRESS = process.env.SUBSCRIPTION_CORE_ADDRESS || null;
const USDC_TOKEN_SYMBOL = 'USDC';
const USDC_TOKEN_DECIMALS = 6;
const USDC_MONTHLY_PRICE_UNITS = BigInt(process.env.USDC_MONTHLY_PRICE_UNITS || '9990000');
const AUTO_RENEW_APPROVAL_MONTHS = Number(process.env.AUTO_RENEW_APPROVAL_MONTHS || 12);

module.exports = {
  AUTO_RENEW_APPROVAL_MONTHS,
  BILLING_PERIOD_DAYS,
  ETH_CHAIN_ID,
  ETH_NETWORK_NAME,
  PLAN_CODES,
  PREMIUM_DURATION_MONTHS,
  RENEWAL_MODES,
  RENEWAL_PROVIDERS,
  RENEWAL_STATUSES,
  SUBSCRIPTION_STATES,
  SUBSCRIPTION_CORE_ADDRESS,
  USDC_MONTHLY_PRICE_UNITS,
  USDC_TOKEN_ADDRESS,
  USDC_TOKEN_DECIMALS,
  USDC_TOKEN_SYMBOL,
};
