CREATE TABLE IF NOT EXISTS abonnement_renouvellement (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  utilisateur_id BIGINT UNSIGNED NOT NULL UNIQUE,
  provider VARCHAR(30) NOT NULL DEFAULT 'ethereum_wallet',
  mode VARCHAR(20) NOT NULL DEFAULT 'manual',
  status VARCHAR(20) NOT NULL DEFAULT 'disabled',
  wallet_address VARCHAR(255) NULL,
  chain_id BIGINT UNSIGNED NULL,
  network VARCHAR(30) NULL,
  smart_contract_address VARCHAR(255) NULL,
  mandate_reference VARCHAR(255) NULL,
  next_renewal_at DATETIME NULL,
  last_renewal_attempt_at DATETIME NULL,
  last_payment_id BIGINT UNSIGNED NULL,
  last_transaction_hash VARCHAR(255) NULL,
  failure_reason VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_abonnement_renouvellement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id),
  CONSTRAINT fk_abonnement_renouvellement_last_payment FOREIGN KEY (last_payment_id) REFERENCES abonnement_paiement(id)
);
